### ISSUE TITLE
panaroo-fmg and panaroo-img don't work for me [Bug??]

### ISSUE THREAD

**Issue by Leytoncito** [gtonkinhill/panaroo#114]
Hello again. I keep exploring the utilities of this tool. I wanted to try panaroo-img and panaroo-fmg, but it returns error messages and warnings.

When I run `panaroo-fmg --tree tree.newick --pa gene_presence_absence.Rtab -o fmg_results.txt`, it returns the following:

/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/estimate_many_genes_params.py:151: RuntimeWarning: invalid value encountered in log
  v) - np.log(1 - np.exp(L_null) - np.exp(L_1)).

On the other hand, when I run `panaroo-img --pa gene_presence_absence.Rtab --tree tree.newick -D 2 -o img_results/`, I get the following in terminal: 
Traceback (most recent call last):
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/bin/panaroo-img", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/estimate_img_params.py", line 580, in main
    result = optimize.basinhopping(f_theory_dist,
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 680, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 619, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 136, in __init__
    self._update_fun()
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 226, in _update_fun
    self._update_fun_impl()
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 133, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 130, in fun_wrapped
    return fun(x, *args)
  File "/home/ubuntu/programas/anaconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/estimate_img_params.py", line 374, in f_theory_dist
    return (np.sqrt(np.sum(np.power(theory - data, 2)) / len(theory)))
**ValueError: operands could not be broadcast together with shapes (117,) (118,)**

I have tried it on two machines, I get the same error. I have panaroo installed in a separate environment. Panaroo is in its version 1.2.3

If you could help me, I will be very grateful.
Thanks in advance
Benjamin  #Leyton

**Comment by gtonkinhill** [comment]
Hi Benjamin,

Sorry for the delay in getting back to you and thanks for flagging this. Would it be possible for you to send me the `tree.newick` and `gene_presence_absence.Rtab` files that cause this error? This would help in working out what the issue is.

**Comment by gtonkinhill** [comment]
I've pushed some updates that should hopefully resolve this issue in v1.2.8

**Comment by actledge** [comment]
I have got the same problem 
ValueError: operands could not be broadcast together with shapes (174,) (301,)

I have installed panaroo1.2.8 with conda
panaroo                   1.2.8              pyhdfd78af_0    bioconda

**Comment by Leytoncito** [comment]
@ Is your newick-file a file that include date collection (dated_phylogeny.newick) ??
I think that's why is doesn't work
Mr @gtonkinhill, how can we generate this type of files?. 
Thanks in advance

**Comment by actledge** [comment]
> @actledge Is your newick-file a file that include date collection (dated_phylogeny.newick) ?? I think that's why is doesn't work Mr @gtonkinhill, how can we generate this type of files?. Thanks in advance
I used the dated tree (*.timetree.nwk) generated by iqtree,
this is my command :
panaroo-img --pa panaroo_out/gene_presence_absence.Rtab -o img_results --tree dated_iqtree.remove_ref.timetree.nwk -D 1

**Comment by ashcoat2** [comment]
@gtonkinhill Hello! I also am getting this same error when trying to run the panaroo-img command. I used a dated newick file that I created from the core sequence alignment outputted by panaroo and the isolate sequencing  dates using IQ-TREE. This is the command that I used for IMG model:
panaroo-img --pa gene_presence_absence.Rtab -o img_results --tree core_gene_alignment.aln.timetree.nwk -D 1
And this is the abbreviated error message:
ValueError: operands could not be broadcast together with shapes (107,) (110,) 
I don't understand why I am getting this error. Do you have any insight to help troubleshoot this?  Thanks!

**Comment by gtonkinhill** [comment]
Hi, 

Apologies for not seeing this thread earlier. When commenting on a closed issue it can be helpful to either re-open it or open a new issue to make it easier to keep track of things.

This could be an issue with the format of the tree but it is hard to determine exactly what is going on without an example. If you are able to send me a small example that reproduces the problem I would be happy to take a look.

Alternatively, for the IMG model [panicmage](https://github.com/fbaumdicker/panicmage) has worked well in the testing that I have done.

I have also been working on a regression based [alternative](https://github.com/gtonkinhill/panstripe) to the pangenome accumulation curve which may be of interest. I am hoping to release the preprint in the next week.
