### ISSUE TITLE
Error to generate network (v 1.2.8)

### ISSUE THREAD

**Issue by rpucheq** [gtonkinhill/panaroo#136]
Hi Gerry, I am using the lastest version of Panaroo 1.2.8, and after running ~250 genomes (4,5 Mb each one) using the command
 `panaroo -i *.gff3 -o results --clean-mode sensitive` I have this error:
```
generating initial network...
Traceback (most recent call last):
  File "/opt/python/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/opt/python/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 303, in main
    G, centroid_contexts, seqid_to_centroid = generate_network(
  File "/opt/python/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/generate_network.py", line 70, in generate_network
    current_cluster = seq_to_cluster[id]
KeyError: '77_41_2'
```
Thanks for your help and congrats for this great tool!.
Best regards
Rafael

**Comment by gtonkinhill** [comment]
Hi,

This is sometimes caused by issues with the input gff files. If you run Panaroo with the `--remove-invalid-genes` flag it might resolve the problem.

**Comment by rpucheq** [comment]
Thanks Gerry, work very fine add this flag!
Rafael
