### ISSUE TITLE
Panaroo-qc

### ISSUE THREAD

**Issue by GillNdhlovu** [gtonkinhill/panaroo#144]
When I run panaroo-qc I get the output below. I am not sure what the issue is, may you please assist. Thank you

gillian.nghlovu@slurm-login:~$ panaroo-qc -t 3 --graph_type all -i /users/gillian.nghlovu/prokka_output/*.gff --ref_db refseq.genomes.k21s1000.msh -o results
/bin/sh: 1: mash: not found
Traceback (most recent call last):
  File "/users/gillian.nghlovu/.local/bin/panaroo-qc", line 11, in <module>
    load_entry_point('panaroo==1.2.9', 'console_scripts', 'panaroo-qc')()
  File "/users/gillian.nghlovu/.local/lib/python3.8/site-packages/panaroo/generate_qc_plots.py", line 451, in main
    generate_qc_plot(method=args.graph_type,
  File "/users/gillian.nghlovu/.local/lib/python3.8/site-packages/panaroo/generate_qc_plots.py", line 355, in generate_qc_plot
    dist_mat, file_names = get_mash_dist(input_gffs=input_files,
  File "/users/gillian.nghlovu/.local/lib/python3.8/site-packages/panaroo/generate_qc_plots.py", line 44, in get_mash_dist
    subprocess.run(mash_cmd, shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mash triangle -p 3 -l /users/gillian.nghlovu/results/tmpp8adizx4 /users/gillian.nghlovu/results/tmpvn74z1b0 > results/mash_dist.txt' returned non-zero exit status 127.

**Comment by gtonkinhill** [comment]
Hi,

It looks like `mash` is not properly installed on your system. If you're using conda you could try running

```
conda install -c bioconda mash
```

**Comment by GillNdhlovu** [comment]
Thank you. I am working from a cluster I cannot use the conda base command. Do you know another way of installing mash?

**Comment by gtonkinhill** [comment]
Hi,

There are also binaries for different operating systems available via the mash website https://mash.readthedocs.io/en/latest/
You will just need to make sure that the program is available on your path.
