### ISSUE TITLE
ValueError: Duplicate ID from NCBI gbk files 

### ISSUE THREAD

**Issue by comingkms** [gtonkinhill/panaroo#195]
Hi,

I tried to compare results of panaroo to PPanGGOLiN using some NCBI gbk files. I had the same issue with #131.  The panaroo version is 1.3.0.  Indeed, panaroo could tranfer gbk files into gff files in the temp folder. However, when it read gff files, it showed "ValueError: Duplicate ID GCA_000959405.1_003250.mRNA.0.CDS.1" Any idea ?

Here is the link for GCA_000959405.1: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000959405.1/
------------------
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 272, in process_prokka_input
    for gff_no, gff in job)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 136, in get_gene_sequences
    from_string=True)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 1405, in create_db
    c.create()
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 543, in create
    self._populate_from_lines(self.iterator)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 624, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 257, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID GCA_000959405.1_003250.mRNA.0.CDS.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/comingkms/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 300, in main
    args.n_cpu, args.table)
  File "/home/comingkms/anaconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 282, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!

-------------------------------
Thanks so much for your help.

**Comment by gtonkinhill** [comment]
Hi,

Thanks for flagging this. Would it be possible to send through the offending gbk file containting the duplicate ID (GCA_000959405.1_003250.mRNA.0.CDS.1)?  This would help in getting the issue resolved faster.

**Comment by gtonkinhill** [comment]
Hi,

Looking at the GFF file it looks like there are indeed duplicate entries for the same gene with different frameshifts.  

```
NZ_CP009588.1   Protein Homology        CDS     2260233 2260491 .       -       0       ID=cds-WP_038802950.1-44;Parent=gene-BG99_RS25930;Dbxref=Genbank:WP_038802950.1;Name=WP_038802950.1;Note=programmed frameshift;exception=ribosomal slippage;gbkey=CDS;inference=COORDINATES: similar to AA sequence:RefSeq:WP_086558188.1;locus_tag=BG99_RS25930;product=IS3 family transposase;protein_id=WP_038802950.1;transl_table=11
NZ_CP009588.1   Protein Homology        CDS     2259371 2260233 .       -       2       ID=cds-WP_038802950.1-44;Parent=gene-BG99_RS25930;Dbxref=Genbank:WP_038802950.1;Name=WP_038802950.1;Note=programmed frameshift;exception=ribosomal slippage;gbkey=CDS;inference=COORDINATES: similar to AA sequence:RefSeq:WP_086558188.1;locus_tag=BG99_RS25930;product=IS3 family transposase;protein_id=WP_038802950.1;transl_table=11
```

The GBK/NCBI support is relatively new and Panaroo does not handle frameshifts within gene annotations. This is not a problem for annotations generated using prodigal and Prokka as they are excluded. 

I have now included frameshift annotations in the list of annotations that can be automatically filtered by enabling the `--remove-invalid-genes` flag in Panaroo.

I hope to include this in the next release but if you would like to try it out in the meantime you can install the development version using

```
pip install git+https://github.com/gtonkinhill/panaroo@devel
```

**Comment by comingkms** [comment]
Thanks,  Gerry. I will try it later.
