### ISSUE TITLE
Error reading GFF produced by Bakta

### ISSUE THREAD

**Issue by gracehm** [gtonkinhill/panaroo#201]
Hello,
I've moved from Prokka to Bakta for my genome annotations, and I cannot get past reading the GFFs. I've tried using the different convert to GFF scripts provided but none have solved the issue. 

Thanks.

**Comment by gtonkinhill** [comment]
Hi,

It's not particularly obvious in the docs but Panaroo should support Bakta annotations if you provide the paths to each file in a text file rather than on the command line. 

There is a bit more explanation [here](https://gtonkinhill.github.io/panaroo/#/gettingstarted/quickstart?id=different-input-formats). Please let me know if this doesn't resolve the issue.

**Comment by gracehm** [comment]
Thanks for this! I've tried both with the file input and as a directory, and I have more recently been running into this error code:

`Error reading prokka input!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 289, in __call__
    for func, args, kwargs in self.items]
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 289, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 127, in get_gene_sequences
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 272, in process_prokka_input
    for gff_no, gff in job)
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: Error reading prokka input!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gracemorales/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 300, in main
    args.n_cpu, args.table)
  File "/home/gracemorales/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 282, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
`

Thanks

**Comment by gtonkinhill** [comment]
Hi,

If possible it would be great if you could attach a small reproducible example including the exact command you ran. It's a bit tricky to work out what the issue is from this error message.

**Comment by gracehm** [comment]
Sure, I've been running this command: "panaroo -i ~/GFF/*.gff3 -o ~/panarooprokka --clean-mode moderate -t 48 -a core --remove-invalid-gene --core_threshold 0.99"

It ran once before just fine, and then it has failed every other time after. I am also attaching a few of the GFF files (attached as txt files here since I can't attach as .gff3 files).
[EC28.txt](https://github.com/gtonkinhill/panaroo/files/9788165/EC28.txt)
[EC304.txt](https://github.com/gtonkinhill/panaroo/files/9788166/EC304.txt)

**Comment by gtonkinhill** [comment]
Hi,

I have had trouble reproducing the error you mentioned using panaroo v1.3.0. I repeatedly ran the command you copied on the two files and occasionally hit an issue due to the very large number of CPU cores you requested. I don't believe this is the same issue you have but it might be worth requesting a smaller number of cpus.

An alternative thing to try might be to run Panaroo  in its alternative input mode by providing a list of input files rather than giving them on the command line.

In this example you would run 

```
panaroo -i input_files.txt -o ~/panarooprokka --clean-mode moderate -t 48 -a core --remove-invalid-gene --core_threshold 0.99
```

where `input_files.txt` contained the file paths as

```
~/GFF/EC28.gff3
~/GFF/EC304.gff3
```
