### ISSUE TITLE
Error with panaroo-generate-gffs 

### ISSUE THREAD

**Issue by sarapita** [gtonkinhill/panaroo#212]
I'm trying to update my bakta gffs after panaroo 1.3.0 proccessing with the following command:

panaroo-generate-gffs -o panaroo_out -i *gff3 -t 1

However, I keep getting the following error:

Traceback (most recent call last):
  File "/services/tools/panaroo/1.3.0/bin/panaroo-generate-gffs", line 10, in <module>
    sys.exit(main())
  File "/services/tools/panaroo/1.3.0/lib/python3.10/site-packages/panaroo/post_run_gff_output.py", line 277, in main
    parsed_gffs = parse_all_gffs(isolate_names, args.input_files, args.verbose)
  File "/services/tools/panaroo/1.3.0/lib/python3.10/site-packages/panaroo/post_run_gff_output.py", line 84, in parse_all_gffs
    input_file = next((s[1] for s in zip(base_input, input_list) if isolate_id == s[0]))
StopIteration

Any idea on how I should address it or what might be causing it?

Thanks in advance!

Best,
Sara

**Comment by gtonkinhill** [comment]
Hi,

I am afraid I have only tested the updating of GFFs on Prokka output. I hope to extend this to Bakta GFFs soon so I will leave this issue open as a feature request and update it when the functionality is added.

**Comment by sarapita** [comment]
Ah, I see thanks.

**Comment by vonMentzer-Group** [comment]
Can you run panaroo on bakta annotated genomes?

**Comment by gtonkinhill** [comment]
Yes, it should be possible using the `--remove-invalid-genes` option. We are hoping to enable panaroo to take advantage of some of the extra features of Bakta soon.

**Comment by limrp** [comment]
> Yes, it should be possible using the `--remove-invalid-genes` option. We are hoping to enable panaroo to take advantage of some of the extra features of Bakta soon.

Hi!

I'm new to this field and I was using bakta to annotate my genomes. I wanted to use their gff3 files to run panaroo. I keep getting an error, but after using the `--remove-invalid-genes` parameter recommended here, it all worked!. 

I wanted to ask if prokka gff3 files don't need the use of the `--remove-invalid-genes` parameter. 

If so, why? What is the difference with the gff3 from Bakta. 

Thank you so much for your amazing tool and for all your work!

**Comment by nbat64** [comment]
Hello,
Will you make an update to run panaroo-generate-gffs on Bakta gff3? I have the error reported sarapita.
Thanks

**Comment by gtonkinhill** [comment]
Hi, 

Have you run Panaroo as recommended above with the `--remove-invalid-genes ` parameter?

**Comment by nbat64** [comment]
Hi yes, I used this parameter. 
So I was able to run part of Piggy from Panaroo outputs. I created a folder named fixed_input_files/ where I copied the gff (tried to use panaroo-generate-gffs but doesn't work with Backta input).
Piggy run correctly for part of the pipeline. But it failed at the step `piggy-roary-piggy-combiner.pl` as it looks in the file `gene_presence_absence.csv` for a column in Roary version indicating single copy gene (6th column `Average Sequence per Isolate`  value must be 1).
I am trying to edit Panaroo `gene_presence_absence.csv` with a new column with this info of single copy gene. Do Panaroo give us this information in an output somewhere? `panaroo-filter-pa`with `--type frag`

Thanks

**Comment by gtonkinhill** [comment]
I'm afraid we don't directly support integration with Piggy at the moment. You might be able to use the 'gene_presence_absence_roary.csv' file.

**Comment by nbat64** [comment]
Hi, 
I used `gene_presence_absence_roary.csv` with some edits (added `""`around values and for colunm `Average Sequence per Isolate` changed 1.0 and 2.0 to 1 and 2 ) and was able to run Piggy. If others peoples want to have a try.

**Comment by gtonkinhill** [comment]
Thanks for the update! I'll look into whether we can add this in automatically.

**Comment by BiologicalScientist** [comment]
I encountered this error message as well. (panaroo successfully ran with .gff3 output from Bakta using the `--remove-invalid-genes` parameter, `panaroo-generate-gffs` script failed with the error message 
```
  File "/Volumes/Scratch_Drive/conda_envs/panaroo152/lib/python3.9/site-packages/panaroo/post_run_gff_output.py", line 81, in parse_all_gffs
    input_file = next((s[1] for s in zip(base_input, input_list) if isolate_id == s[0]))
StopIteration
```

 I think the issue stems from line 80 preceding the error message line of the post_run_gff_output.py script which replaces ".gff" in the base input with "". If the input file is a gff3 file (like the default for bakta) then it won't be the correct key in base_input as there will be an extra 3 in the name.

https://github.com/gtonkinhill/panaroo/blob/0fc3d0c5cfdae1815a368cbe47edad43bca46d37/panaroo/post_run_gff_output.py#L69C1-L80C79
```        
#get the right file in the original processing order
        base_input = [os.path.basename(input_id) for input_id in input_list]
        base_input = [input_id.replace(".gff", "") for input_id in base_input]
        input_file = next((s[1] for s in zip(base_input, input_list) if isolate_id == s[0]))
```

`        base_input = [input_id.replace(".gff", "") for input_id in base_input]`

changing the filenames to .gff fixed the error in my usecase but presumably changing the line of code to account for the .gff3 extension may also work. There are some other errors that popped up still after this change which could be fixed by adapting the approach from issue #259 with a couple of tweaks. I did the following to try and tidy up the bakta gffs so they worked with the panaroo-generate-gffs script and it ran.

1. remove single # comments, non-essential features and remove ##FASTA from this line
`for i in bakta_gffs/*.gff3; do grep -Ev '^\# ' $i | grep -Ev '^\#\#feature\-ontology ' | grep '^\#' | sed \$d > Fixed_${i%3}; done `
2. add in all the non comment lines (removing non-essential features and no fasta file details)
`for i in bakta_gffs/*.gff3; do grep -Ev '^\# ' $i | grep -Ev '^\#\#feature\-ontology ' | grep -v '^\#' | sed '/^>/q' | sed \$d  >> Fixed_${i%3}; done`
3. need to insert a line "##FASTA" plus everything afterwards
`for i in bakta_gffs/*.gff3; do sed -n '/##FASTA/,$p' "$i" >> Fixed_${i%3}; done`

4. run 
`panaroo-generate-gffs -i  Fixed_bakta_gffs/*.gff -f prokka -o panaroo_dir`

**Comment by Dx-wmc** [comment]
I am still encountering this issue when using bakta's GFF files. Will it be fixed?

**Comment by nzmacalasdair** [comment]
We have recently made some commits with the aim of fixing issues arising from using Bakta GFF files with `panaroo-generate-gffs`, which will be included in the next release.
