### ISSUE TITLE
Not recognising gff files

### ISSUE THREAD

**Issue by BenEvans47** [gtonkinhill/panaroo#236]
Hi,

I am trying to run Panaroo on our HPC using the following submission:

#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=XXX@uea.ac.uk
#SBATCH --job-name=panaroo
#SBATCH -o panaroo-%j.out
#SBATCH -e panaroo-%j.err
#SBATCH -t 3-00:00:00
#SBATCH --mem 120G
#SBATCH -p compute-24-128
#SBATCH --ntasks=24
#SBATCH --ntasks-per-node=24

source activate panaroo

panaroo -i CP075811.gff -o results/ --clean-mode strict -a core --aligner mafft -t 24

module purge

I am getting an error that suggest panaroo cannot recognise the gff file. The gff files were all generated in Prokka. The full error message is below. Any help would be much appreciated!

Best wishes,

Ben

  0%|          | 0/5022 [00:00<?, ?it/s]
  0%|          | 0/5022 [00:01<?, ?it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 93, in get_gene_sequences
    gff_file = open(gff_file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '##gff-version 3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 244, in process_prokka_input
    gene_sequence_list = Parallel(n_jobs=n_cpu)(
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '##gff-version 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 286, in main
    process_prokka_input(args.input_files, args.output_dir,
  File "/gpfs/home/tmd16gfu/.conda/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 256, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!

**Comment by mabouelk** [comment]
I have the same issue 
raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!


any help?
