### ISSUE TITLE
Error while generating gffs from panaroo output

### ISSUE THREAD

**Issue by cizydorczyk** [gtonkinhill/panaroo#239]
I get the following error while trying to generate simplified gffs using panaroo-generate-gffs:

```
$ panaroo-generate-gffs -i formatted-gff/*.gff -o ./
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 8329/8329 [00:42<00:00, 195.92it/s]
  0%|                                                                                                            | 0/227 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/conrad/anaconda3/envs/panaroo-env/bin/panaroo-generate-gffs", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.3.3', 'console_scripts', 'panaroo-generate-gffs')())
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/panaroo-1.3.3-py3.10.egg/panaroo/post_run_gff_output.py", line 302, in main
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/panaroo-1.3.3-py3.10.egg/panaroo/post_run_gff_output.py", line 168, in create_new_gffs
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/panaroo-1.3.3-py3.10.egg/panaroo/post_run_gff_output.py", line 111, in parse_gff_body
IndexError: list index out of range
  0%|                                                                                                            | 0/227 [00:00<?, ?it/s]
```

Any ideas what might be causing the issue? I have not edited/changed any of the files in the panaroo output directory.

**Comment by cizydorczyk** [comment]
Part of the problem was bakta's comment lines starting with a single '#'. Replacing these with two '##' let it run for some genomes but then broke again. Not sure what the issue is for these other genomes...

**Comment by cizydorczyk** [comment]
The issue seemed to be caused by some non-ASCII characters in the Bakta output. Removing them solved the problem.

New problem:
```
$ panaroo-generate-gffs -i formatted-gff/*.gff -o ./ -t 6 --verbose
Loading panaroo output and input gff files...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 227/227 [00:05<00:00, 42.79it/s]
Cross-referencing input gffs and the pangenome...
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 8329/8329 [00:42<00:00, 197.14it/s]
Creating new gff files...
 69%|███████████████████████████████████████████████████████████████████▎                              | 156/227 [09:42<04:49,  4.08s/it]Uh Oh, too much data
[{'seqid': 'NC_011770.1', 'type': 'CDS', 'start': '1393840', 'end': '1393911', 'score': '.', 'strand': '+', 'phase': '0', 'ID': 'cds-WP_010895661.1', 'inference': 'COORDINATES: similar to AA sequence:RefSeq:YP_003933612.1', 'Locus_tag': 'PLES_RS06625'}, {'seqid': 'NC_011770.1', 'type': 'CDS', 'start': '1393913', 'end': '1394935', 'score': '.', 'strand': '+', 'phase': '0', 'ID': 'cds-WP_010895661.1', 'inference': 'COORDINATES: similar to AA sequence:RefSeq:YP_003933612.1', 'Locus_tag': 'PLES_RS06625'}]
 71%|█████████████████████████████████████████████████████████████████████▉                            | 162/227 [10:06<04:21,  4.02s/it]Traceback (most recent call last):
  File "/home/conrad/anaconda3/envs/panaroo-env/bin/panaroo-generate-gffs", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.3.3', 'console_scripts', 'panaroo-generate-gffs')())
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/panaroo-1.3.3-py3.10.egg/panaroo/post_run_gff_output.py", line 302, in main
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/conrad/anaconda3/envs/panaroo-env/lib/python3.10/site-packages/panaroo-1.3.3-py3.10.egg/panaroo/post_run_gff_output.py", line 207, in create_new_gffs
TypeError: list indices must be integers or slices, not str
 74%|████████████████████████████████████████████████████████████████████████                          | 167/227 [10:12<03:39,  3.67s/it]
```

**Comment by cizydorczyk** [comment]
Looks like the issue was a Genbank GFF file (as usual).

**Comment by gtonkinhill** [comment]
Thanks very much for letting me know what caused the issue. We are hoping to improve Panaroo's support for Bakta annotations soon so this is very helpful.
