### ISSUE TITLE
cd-hit error 

### ISSUE THREAD

**Issue by albbaous** [gtonkinhill/panaroo#241]
This is the error I am getting which makes no sense to me. 

 File "/gpfs01/home/user/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/gpfs01/home/user/miniconda3/envs/panaroo/lib/python3.6/site-packages/panaroo/__main__.py", line 323, in main
    n_cpu=args.n_cpu)
  File "/gpfs01/home/user/miniconda3/envs/panaroo/lib/python3.6/site-packages/panaroo/cdhit.py", line 91, in run_cdhit
    subprocess.run(cmd, shell=True, check=True)
  File "/gpfs01/home/user/miniconda3/envs/panaroo/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd-hit -T 40 -i results/combined_protein_CDS.fasta -o results/combined_protein_cdhit_out.txt -c 0.3 -s 0.98 -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999 -g 1 -n 2' return$

This is what I am running 
# running panaroo
mkdir results
panaroo -i *.gff -o results --clean-mode sensitive -c 0.3 -a core --aligner clustal --core_threshold 0.98 -t 40

my files are all prokka annotated!!!!!

**Comment by gtonkinhill** [comment]
Hi,

Panaroo was not designed to run with an initial clustering identity as low as 30% This is very low and will likely result in many different genes being incorrectly clustered together. I would remove the `-c 0.3` flag from your command and see if it runs.

If this doesn't resolve things you can try running the cd-hit command separately to see if it provides additional information on what is causing the issue.

**Comment by NazMemon** [comment]
I am also getting same error. Although initially I am just trying to compare 3 genome files. My .gff files are prokka annotated. 
The syntax I have used is the basic one. I am using google compute engine with 8 cores and around 500 GB memory so there is also no any issues of Ram or memory shortage. 


mkdir results
panaroo -i *.gff -o results --clean-mode strict


Approximated maximum memory consumption: 32M
writing new database
writing clustering information
program completed !
Total CPU time 5.51
generating initial network...
Processing paralogs...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 676.74it/s]
collapse mistranslations...
Traceback (most recent call last):
  File "/home/naz/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/naz/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/__main__.py", line 358, in main
    G = collapse_families(G,
  File "/home/naz/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/clean_network.py", line 113, in collapse_families
    cdhit_clusters = iterative_cdhit(G,
  File "/home/naz/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/cdhit.py", line 411, in iterative_cdhit
    run_cdhit_est(input_file=temp_input_file.name,
  File "/home/naz/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/cdhit.py", line 147, in run_cdhit_est
    subprocess.run(cmd, shell=True, check=True)
  File "/home/naz/miniconda3/envs/panaroo/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd-hit-est -T 1 -i /home/naz/Desktop/bac_fragilis_fna/output/Gff3 Genomes/xc/results/tmp3e59iwf5/tmpl8dw_eq_ -o /home/naz/Desktop/bac_fragilis_fna/output/Gff3 Genomes/xc/results/tmp3e59iwf5/tmptfuszo97 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' returned non-zero exit status 1.

**Comment by gtonkinhill** [comment]
Hi,

Please open a separate issue when reporting a new error as it is hard to keep track of comments in older issues. I am not sure if you were able to resolve the problem but you could try running the last command in the error to see if it provides additional information into what went wrong. In this case that would be

```
cd-hit-est -T 1 -i /home/naz/Desktop/bac_fragilis_fna/output/Gff3 Genomes/xc/results/tmp3e59iwf5/tmpl8dw_eq_ -o /home/naz/Desktop/bac_fragilis_fna/output/Gff3 Genomes/xc/results/tmp3e59iwf5/tmptfuszo97 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7
```
