### ISSUE TITLE
cd-hit error in first run of Panaroo

### ISSUE THREAD

**Issue by chahatupreti** [gtonkinhill/panaroo#253]
Hi,

Thank you for this wonderful tool! I just created a new conda environment and installed panaroo. I ran `panaroo -i *.gff -o panaroo_results --clean-mode strict -t 16
` 
It ended with the error - 
`Processing paralogs...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2174/2174 [13:40<00:00,  2.65it/s]
collapse mistranslations...
Traceback (most recent call last):
  File "/home/chahatupreti/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/chahatupreti/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 360, in main
    G = collapse_families(G,
  File "/home/chahatupreti/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/clean_network.py", line 113, in collapse_families
    cdhit_clusters = iterative_cdhit(G,
  File "/home/chahatupreti/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/cdhit.py", line 411, in iterative_cdhit
    run_cdhit_est(input_file=temp_input_file.name,
  File "/home/chahatupreti/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/cdhit.py", line 147, in run_cdhit_est
    subprocess.run(cmd, shell=True, check=True)
  File "/home/chahatupreti/anaconda3/envs/panaroo/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd-hit-est -T 16 -i /media/chahatupreti/Raw HT Sequencing Data Backup1/nonhuman_Efs_project/ncbi_dataset/prokka_for_all_selected/selected400gff/panaroo_results/tmppnmrohej/tmpmagx_vbi -o /media/chahatupreti/Raw HT Sequencing Data Backup1/nonhuman_Efs_project/ncbi_dataset/prokka_for_all_selected/selected400gff/panaroo_results/tmppnmrohej/tmpljsq26iw -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' returned non-zero exit status 1.`

Any idea how I can solve this? Based on your suggestion on some other questions here, I tried running the cd-hit command which was causing the issue but that did not throw any error.
Thank you!

**Comment by gtonkinhill** [comment]
Hi, this is likely to be a problem with the installation. 
I was unable to reproduce the previous error with the files provided by the user.

I would recommend trying to reinstall Panaroo in a clean conda environment and making sure that there are no other versions of CD-HIT installed that could be interfering with the program.
