### ISSUE TITLE
RuntimeError: Error reading prokka input!

### ISSUE THREAD

**Issue by mabouelk** [gtonkinhill/panaroo#261]
Panaroo doesn't read any gff outputs. Is panaroo still in service/ supported? 

Error reading prokka input!
Traceback (most recent call last):
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/prokka.py", line 294, in process_prokka_input
    gene_sequence_list = Parallel(n_jobs=n_cpu)(
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/prokka.py", line 148, in get_gene_sequences
    parsed_gff = gff.create_db(clean_gff_string(split[0]),
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/gffutils/create.py", line 1401, in create_db
    c.create()
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/gffutils/create.py", line 543, in create
    self._populate_from_lines(self.iterator)
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/gffutils/create.py", line 669, in _populate_from_lines
    raise EmptyInputError("No lines parsed -- was an empty file provided?")
gffutils.exceptions.EmptyInputError: No lines parsed -- was an empty file provided?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/__main__.py", line 314, in main
    process_prokka_input(args.input_files, args.output_dir,
  File "/home/exouser/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/prokka.py", line 306, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!

**Comment by btreynor** [comment]
I am having a similar issue.  If you come to a solution, please let me know.

**Comment by gtonkinhill** [comment]
Yes, Panaroo is still being supported. This problem is likely caused by an issue with the formatting of the input GFF files.

You could try adding the flag `--remove-invalid-genes` when running Panaroo which should exclude entries that are not supported.

**Comment by btreynor** [comment]
@gtonkinhill I tried that numerous times and had no luck.  Any other suggestions?

**Comment by nzmacalasdair** [comment]
Just to add, I think this could be caused by a single bad GFF file, for instance one file from of a batch annotation on an incomplete/failed assembly. Running with a single thread and watching the progress counter in the `pre-processing gff3 files...` step of panaroo can help identify which file.

**Comment by NicaraoD** [comment]
Same issue, please share the solution if the issue was resolved
