### ISSUE TITLE
Not running with prokka generated gff files

### ISSUE THREAD

**Issue by EdwinDNavarroMonserrat** [gtonkinhill/panaroo#296]
Hello,
I get the following error when running panaroo using prokka generated gff files. Any suggestions on why this is happening?

Running Panaroo
/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(
pre-processing gff3 files...
  0%|          | 0/5 [00:01<?, ?it/s]
Error reading prokka input!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 148, in get_gene_sequences
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 309, in process_prokka_input
    gene_sequence_list = Parallel(n_jobs=n_cpu)(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
RuntimeError: Error reading prokka input!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/panaroo/__main__.py", line 338, in main
    process_prokka_input(args.input_files, args.output_dir,
  File "/users/PZS1114/navarromonserrat/miniforge3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 321, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
Panaroo encountered an error

**Comment by gtonkinhill** [comment]
Hi,

It looks like there might be a problem with one of your GFF files. It is very hard to diagnose this without looking at the gff files and the command you used to run Panaroo.

Alternatively, this might have something to do with the version of BioPython you have installed. You could try installing an older version to address this

```
pip install biopython==1.80
```

If changing the BioPython version works, please let me know as I can update the main Panaroo code to address this issue.

**Comment by EdwinDNavarroMonserrat** [comment]
I changed the bippython version but I still get the same error. I assume the issue is with my gff files due to the error prompt. 

The command I ran is:
panaroo -i *.gff -o panaroo_results --clean-mode strict -a core --aligner clustal --core_threshold 0.98 -t 10

I've attached some gff files that were generated using Prokka.

[Subset.gff.zip](https://github.com/user-attachments/files/15841239/Subset.gff.zip)

**Comment by gtonkinhill** [comment]
Hi,

It appears that your GFF files are missing the FASTA sequences for each contig, which are typically appended to the end when running Prokka. For options to provide these sequences separately, you can refer to the [Panaroo docs](https://gthlab.au/panaroo/#/gettingstarted/quickstart?id=different-input-formats).

**Comment by EdwinDNavarroMonserrat** [comment]
Thanks for the feedback, really appreciate it. Got the script to work.

**Comment by kinchuhrithik** [comment]
> Thanks for the feedback, really appreciate it. Got the script to work.

Hii Edwin I am having the same issue, can you please share how you fixed it? Are you giving a list as the input with .gff <delimited> .fna file? I tried doing this way its still showing this issue.
