### ISSUE TITLE
"NameError: Duplicate entry!!!" with a specific GenBank genome

### ISSUE THREAD

**Issue by qianxuans** [gtonkinhill/panaroo#298]
Hi, 
I've successfully run Panaroo with thousands of genomes, but I'm encountering an issue with a specific GenBank genome (accession number: GCA_000027045.1).The run works perfectly without this specific genome.

## Environment
- Panaroo version: panaroo 1.5.0
- Python version: 3.9
- Operating System: Red Hat Enterprise Linux 9.1 (Plow)     
- Kernel: Linux 5.14.0-162.6.1.el9_1.x86_64
- Architecture: x86-64

## Steps to Reproduce
1. Download GenBank genome assemblies and corresponding GFF files.
2. Use `convert_refseq_to_prokka_gff.py` to combine and convert fna and gff files to Prokka-format gff files.
3. Run Panaroo with the following command:
```
panaroo -i /path/to/gff/*.gff3 -o /path/to/output/ -t 1 --clean-mode sensitive --no_clean_edges --remove-invalid-genes
```
## Error
When including the genome GCA_000027045.1, the following error occurs:
```
trimming contig ends...
refinding genes...
Number of searches to perform:  1134569
Searching...
^M0it [00:00, ?it/s]joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/sheq/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/find_missing.py", line 296, in search_gff
    raise NameError("Duplicate entry!!!")
NameError: Duplicate entry!!!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sheq/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/sheq/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 432, in main
    G = find_missing(G,
  File "/home/sheq/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/find_missing.py", line 96, in find_missing
    all_hits, all_node_locs, max_seq_lengths = zip(*Parallel(n_jobs=n_cpu)(
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/sheq/.local/lib/python3.9/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
NameError: Duplicate entry!!!
```

## Attached files
  - fna file:  GCA_000027045.1_ASM2704v1_genomic.fna
  - Original gff file: GCA_000027045.1.gff
  - Converted gff file: converted_GCA_000027045.1.gff3
[GCA_000027045.1.zip](https://github.com/user-attachments/files/16113117/GCA_000027045.1.zip)

**Comment by gtonkinhill** [comment]
Hi, 

Thank you for the detailed report. I think this may be due to duplicate IDs in your GFF file. The `convert_refseq_to_prokka_gff.py` script does not currently deal with these.

It should be possible to edit the GFF to ensure there are no duplicate IDs which will allow Panaroo to run.
