### ISSUE TITLE
Invalid file extension

### ISSUE THREAD

**Issue by baromagnoli** [gtonkinhill/panaroo#315]
Here is my input:

panaroo -i /home/barbara/documents/comparative_genomics/resultados_prokka/genoma1_prokka/PROKKA_11122024.gff -o results_SeT --clean-mode strict -a core --aligner mafft

What I got:

Checking file: ##gff-version, extension: None
Traceback (most recent call last):
  File "/home/barbara/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/barbara/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 334, in main
    files.append(create_temp_gff3(line[0], line[1], temp_dir))
  File "/home/barbara/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 102, in create_temp_gff3
    raise RuntimeError(f"Invalid file extension! ({ext})")
RuntimeError: Invalid file extension! ()

How can I solve this if I'm already using a .gff generated by Prokka? Also I already checked the version of .gff and everything is alright, including all versions needed

**Comment by gtonkinhill** [comment]
Hi,

It looks like you are running Panaroo on only a single isolate/GFF file. Panaroo requires multiple genomes as input.

**Comment by baromagnoli** [comment]
yes! It worked, thank you!
