### ISSUE TITLE
Running panaroo with pgap created gb files

### ISSUE THREAD

**Issue by erinyoung** [gtonkinhill/panaroo#316]
I am trying to run panaroo on some gb files that have been annotated with pgap. I only have .sqn and .gb files for these.

From the documentation, it seemed like panaroo would work with these, but I am encountering an error.

```
$ panaroo -i GAS2084*.gb -t 48 -o test --remove-invalid-genes --clean-mode moderate
pre-processing gff3 files...
  0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Problem reading GFF3 file:  GAS20844.bgpipe.output_3356416.gb
Problem reading GFF3 file:  GAS20847.bgpipe.output_2524816.gb
Problem reading GFF3 file:  GAS20840.bgpipe.output_3398733.gb
Problem reading GFF3 file:  GAS20841.bgpipe.output_2516329.gb
Problem reading GFF3 file:  GAS20845.bgpipe.output_3362689.gb
  0%|                                                                                                                                                                  | 0/1 [00:03<?, ?it/s]
Error reading prokka input!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 148, in get_gene_sequences
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 309, in process_prokka_input
    gene_sequence_list = Parallel(n_jobs=n_cpu)(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
RuntimeError: Error reading prokka input!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eriny/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/panaroo/__main__.py", line 342, in main
    process_prokka_input(args.input_files, args.output_dir,
  File "/home/eriny/miniconda3/envs/panaroo/lib/python3.11/site-packages/panaroo/prokka.py", line 321, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!

```

I installed panaroo via conda.

```
$ panaroo --version
panaroo 1.5.1

```

**Comment by gtonkinhill** [comment]
Hi,

Panaroo can only handle these file types if they are compliant with Genbank/ENA/DDJB. To use non-standard files you must also provide the input file as a list in a text file (one per line).  

i.e.

```
panaroo -i input_files.txt -t 48 -o test --remove-invalid-genes --clean-mode moderate
```

where `input_files.txt` is formatted with the path to one file per line
