### ISSUE TITLE
panaroo-spydrpick

### ISSUE THREAD

**Issue by samlipworth** [gtonkinhill/panaroo#49]
I have run the main part of panaroo without issue but when trying to run panaroo-spydrpick I get an error:

`panaroo-spydrpick -i gene_presence_absence.csv -o coevo/ --tree ../fastas/mashtree 
Traceback (most recent call last):
  File "/well/bag/users/lipworth/miniconda3/envs/roary/bin/panaroo-spydrpick", line 10, in <module>
    sys.exit(main())
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/panaroo/spydrpick.py", line 246, in main
    pa_matrix, gene_names, sample_names = read_presence_absence(args.pa_file)
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/panaroo/spydrpick.py", line 12, in read_presence_absence
    matrix_txt = np.loadtxt(filename, dtype=str, delimiter=",", comments=None)
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1084, in read_data
    % line_num)
ValueError: Wrong number of columns at line 2
`
I thought maybe this was due to the format of the csv file so I also tried the gene_presence_absence _roary.csv file:

`panaroo-spydrpick -i gene_presence_absence_roary.csv -o coevo/ --tree ../fastas/mashtree 
[False False False ...  True  True  True]
881
[881 881 881 ...   1   1   1]
Traceback (most recent call last):
  File "/well/bag/users/lipworth/miniconda3/envs/roary/bin/panaroo-spydrpick", line 10, in <module>
    sys.exit(main())
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/panaroo/spydrpick.py", line 259, in main
    chunk_size=100)
  File "/well/bag/users/lipworth/miniconda3/envs/roary/lib/python3.7/site-packages/panaroo/spydrpick.py", line 117, in spydrpick
    mi = mi_00 * (np.log(mi_00) - np.log(mi_1) - np.log(mi_0))
ValueError: operands could not be broadcast together with shapes (100,37990) (37990,1) `

any idea how I can get this to work? Happy to share the data

**Comment by gtonkinhill** [comment]
Sorry for the delay in getting back to you on this. This bug should be fixed in the latest release.
