### ISSUE TITLE
Panaroo-qc ValueError

### ISSUE THREAD

**Issue by Antonia-Chalka** [gtonkinhill/panaroo#69]
I installed panaroo in a conda environment. When trying to run panaroo-qc for a set of sequences I get the following error:

> Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/gally_grp/annita/anaconda/envs/panaroo_env/bin/panaroo-qc", line 6, in <module>
    exit(main())
  File "/exports/cmvm/eddie/eb/groups/gally_grp/annita/anaconda/envs/panaroo_env/lib/python3.7/site-packages/panaroo/generate_qc_plots.py", line 441, in main
    ref_db=args.ref_db)
  File "/exports/cmvm/eddie/eb/groups/gally_grp/annita/anaconda/envs/panaroo_env/lib/python3.7/site-packages/panaroo/generate_qc_plots.py", line 350, in generate_qc_plot
    quiet=True)
  File "/exports/cmvm/eddie/eb/groups/gally_grp/annita/anaconda/envs/panaroo_env/lib/python3.7/site-packages/panaroo/generate_qc_plots.py", line 53, in get_mash_dist
    dist_mat[i, j] = float(d)
ValueError: could not convert string to float: 'version'

From what I understand it seems to be a simple case of type casting, so it should be an easy fix.

**Comment by gtonkinhill** [comment]
Hi, I'm having trouble reproducing this error. Can you confirm the version of `mash` that is installed? 

Running `mash --version` should give `2.2.2`

**Comment by Antonia-Chalka** [comment]
Hi,
Thank you for your quick response. Turns out I had mash 1.1 installed, and after updating to 2.2.2 panaroo-qc is working perfectly.
Thanks again and apologies for the incovenience.
