### ISSUE TITLE
mark genomes as circular

### ISSUE THREAD

**Issue by alexweisberg** [gtonkinhill/panaroo#84]
Hi,

I really like the reference genome layout example from the wiki and am replicating that with my own data. The graph network looks good, however all of the genomes are rendered as linear molecules. Is there a way to indicate in the input gff3 files that all or some replicons are circular? I tried adding a region line with is_circular=true however that resulted in a key error exception:

Traceback (most recent call last):
  File "/local/cluster/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'group_9859'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Software/panaroo/scripts/reference_based_layout.py", line 219, in <module>
    layout(**vars(args))
  File "/Software/panaroo/scripts/reference_based_layout.py", line 128, in layout
    mapping, ref_g_id, max_dist)
  File "/Software/panaroo/scripts/reference_based_layout.py", line 32, in add_to_queue
    "gene_id"], max_dist)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/local/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'group_9859'

 This error does not happen if I run it without a region line. Thanks!

**Comment by gtonkinhill** [comment]
Hi,

Plotting circular replicons is a little tricky as the input to the algorithm is linear contigs. This is sometimes resolved when multiple contigs span the entire loop but is not always the case.

When I have run into this in the past I have manually added an edge in cytoscape to complete a loop and improve the plotting layout.

**Comment by alexweisberg** [comment]
Hi,

Thank you. I will manually add the edge for my reference genome and see how it resolves. It might be a nice feature to add (recognizing is_circular or some flag) though I understand it may be tricky to implement due to incomplete genomes or those with plasmids.
