### ISSUE TITLE
TypeError: bfs_edges() got an unexpected keyword argument 'depth_limit'

### ISSUE THREAD

**Issue by MostafaYA** [gtonkinhill/panaroo#86]
Hi, 

I got the following error when running panaroo. The installation was done via conda. 
I have no clue where the problem could be and would apprciate help!!

Thanks 

> `panaroo -i ./*.gff -o results --clean-mode  strict`
```
pre-processing gff3 files...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.44s/it]
running cmd: cd-hit -T 1 -i results/combined_protein_CDS.fasta -o results/combined_protein_cdhit_out.txt -c 0.98 -s 0.98 -aL 0.0 -AL 99                                                                                                      999999 -aS 0.0 -AS 99999999 -M 0 -d 999 -g 1 -n 2
================================================================
Program: CD-HIT, V4.7 (+OpenMP), Jul 13 2018, 17:17:44
Command: cd-hit -T 1 -i results/combined_protein_CDS.fasta -o
         results/combined_protein_cdhit_out.txt -c 0.98 -s 0.98
         -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999
         -g 1 -n 2

Started: Sun Oct 18 16:09:54 2020
================================================================
                            Output
----------------------------------------------------------------
Your word length is 2, using 5 may be faster!
total seq: 17664
longest and shortest : 2643 and 29
Total letters: 5533793
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 7M
Buffer          : 1 X 11M = 11M
Table           : 1 X 0M = 0M
Miscellaneous   : 0M
Total           : 19M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 246821500

comparing sequences from          0  to      17664
..........    10000  finished       3200  clusters
.......
    17664  finished       6101  clusters

Apprixmated maximum memory consumption: 26M
writing new database
writing clustering information
program completed !

Total CPU time 8.98
generating initial network...
Processing paralogs...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 1799.85it/s]
collapse mistranslations...
Processing depth:  1
Iteration:  1
  0%|                                                                                                         | 0/6112 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mostafa.abdel/tools/conda/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/mostafa.abdel/.local/lib/python3.6/site-packages/panaroo-1.2.4-py3.6.egg/panaroo/__main__.py", line 334, in main
  File "/home/mostafa.abdel/.local/lib/python3.6/site-packages/panaroo-1.2.4-py3.6.egg/panaroo/clean_network.py", line 182, in collapse_families
TypeError: bfs_edges() got an unexpected keyword argument 'depth_limit'
```

**Comment by gtonkinhill** [comment]
Hi,

This looks like it could be an issue with the version of the python networkx module.

If you look at the output of running `pip freeze` it should give a networkx version of at least 2.4
