### ISSUE TITLE
KeyError when running reference_based_layout.py

### ISSUE THREAD

**Issue by bogemad** [gtonkinhill/panaroo#89]
Hi, 

Thanks for writing a great pipeline. I have one error that keeps popping up when I run the reference_based_layout.py script. See below:

```
$ python ~/bin/panaroo/scripts/reference_based_layout.py 0 final_graph.gml capacity_cut_edges.txt --add_reference_edges

<Output with lots of numbers and gene names>

Traceback (most recent call last):
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'bepA_2~~~bepA_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bogemad/bin/panaroo/scripts/reference_based_layout.py", line 219, in <module>
    layout(**vars(args))
  File "/home/bogemad/bin/panaroo/scripts/reference_based_layout.py", line 118, in layout
    queue = add_to_queue(G, nid, G.neighbors(nid), visited, sink, mapping,
  File "/home/bogemad/bin/panaroo/scripts/reference_based_layout.py", line 31, in add_to_queue
    mapping.loc[G.nodes[i]['name'],
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 786, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/generic.py", line 3491, in xs
    loc = self.index.get_loc(key)
  File "/home/bogemad/miniconda3/envs/panaroo_env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'bepA_2~~~bepA_1'
```

Would greatly appreciate any help you can provide.

Cheers,

Daniel

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the delay in getting back to you. 

This is a bit tricky to debug without the input data. Would it be possible to provide a small example dataset that reproduces the issue?

**Comment by bogemad** [comment]
No problem at all. Thanks for getting back to me. 

I've compiled a small dataset that is giving me a similar issue (different homology group but same error). In doing this I realised that this issue is only occurring when I use panaroo-merge as the script works fine on single panaroo runs.

[example_data.tar.gz](https://github.com/gtonkinhill/panaroo/files/5632646/example_data.tar.gz)

Details of how I merged the dataset is below:

Run panaroo in 3 groups: 

group 1: ATCC_33913.gff, B100.gff, ICMP_4013.gff
group 2: 756C.gff, CFBP_2527R.gff, MAFF106181.gff
group 3: PHDS-18-658.gff, PHDS-19-1836-B.gff

**Comment by gtonkinhill** [comment]
Hi,

Sorry for being slow getting back to this. I had to take a break from Panaroo development to finish my PhD thesis.
We have not yet thoroughly tested combining the `reference_based_layout.py` script with the merge graph functionality. However, when trying to reproduce your issue the script appeared to work for me. I used the following commands

```
cd gff
panaroo -i ATCC_33913.gff B100.gff ICMP_4013.gff -o ../group1/ --clean-mode moderate --no_clean_edges -t 10
panaroo -i 756C.gff, CFBP_2527R.gff, MAFF106181.gff -o ../group2/ --clean-mode moderate --no_clean_edges -t 10
panaroo -i PHDS-18-658.gff PHDS-19-1836-B.gff -o ../group3/ --clean-mode moderate --no_clean_edges -t 10

cd ..
panaroo-merge -d group1  group2  group3 -a core --core_threshold 0.9999 -t 40 -o panaroo_merge/

cd panaroo_merge
python ~/panaroo/scripts/reference_based_layout.py 0 final_graph.gml capacity_cut_edges.txt --add_reference_edges
```

This resulted in the following file for input into Cytoscape
[capacity_cut_edges.txt](https://github.com/gtonkinhill/panaroo/files/5870623/capacity_cut_edges.txt)
